openapi: 3.1.0

info:
  title: medical laboratory docs
  version: 1.0.0

servers:
  - url: http://localhost:4500

paths:
  /api/auth/login:
    post:
      operationId: loginUser
      summary: 'получение токена для входа в личный кабинет'
      tags:
        - login
      description: 'вход в личный кабинет'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginData'
      responses:
        200:
          description: 'успешный вход в личный кабинет'
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        403:
          description: 'нахуй пошёл'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - access denied
  /api/auth/register:
    post:
      operationId: registerUser
      summary: 'регистрация'
      tags:
        - register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                middleName:
                  type: string
                surname:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum:
                    - admin
                    - technician
        required: true
      responses:
        200:
          description: 'регистрация пройдена успешно'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /api/user/short:
    get:
      operationId: getShortUser
      summary: 'получение короткой информации о пользователе'
      tags:
        - user
      responses:
        200:
          description: 'регистрация пройдена успешно'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  email:
                    type: string
                  middleName:
                    type: string
                  name:
                    type: string
                  role:
                    type: string
                    enum:
                      - 'admin'
                      - 'technician'
                  surname:
                    type: string

  /api/profile/daily-tasks:
    get:
      operationId: getDailyTasks
      summary: 'получение всех задач на день'
      tags:
        - daily-tasks
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyTask'
  /api/profile:
    get:
      operationId: getProfile
      summary: 'получение основной информации о профиле'
      tags:
        - profile
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'

  /api/knowledge:
    get:
      operationId: getKnowledgeSummary
      summary: 'получение всей базовой информации о базе знаний'
      tags:
        - knowledge
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  doctorsCount:
                    type: number
                  technicalCount:
                    type: number
                  typeWorkCount:
                    type: number
                  categoryTechnicalscount:
                    type: number
  /api/knowledge/doctors:
    get:
      operationId: getDoctors
      summary: 'получение информации о докторах'
      tags:
        - doctors
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doctor'

  /api/knowledge/technicals:
    get:
      operationId: getTechnicians
      summary: 'получение информации о техниках'
      tags:
        - technicals
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Technical'

  /api/knowledge/type-works:
    get:
      operationId: getTypeWorks
      summary: 'получние информации о всех типах работы'
      tags:
        - type-works
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TypeWork'
    post:
      operationId: createTypeWork
      responses:
        200:
          description: ''

  /api/knowledge/category-technicals:
    get:
      operationId: getCategoryTechnicals
      summary: 'получение все информации о категориях техников'
      tags:
        - category-technicals
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryTechnicals'

  /api/storage:
    get:
      operationId: getStorageInfo
      summary: получение всей информации о складе
      tags:
        - storage
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageItem'
  /api/salary:
    get:
      operationId: getPayrollData
      summary: 'получение всех заплат рабочих'
      tags:
        - salary
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PayrollData'

  # НОВЫЕ МАРШРУТЫ ДЛЯ COURIER TASK
  /api/courierTask:
    post:
      operationId: createCourierTask
      summary: 'Создание новой задачи для курьера'
      tags:
        - courier-tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourierTaskDTO'
      responses:
        201:
          description: 'Задача успешно создана'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourierTask'
        400:
          description: 'Некорректные данные'
    get:
      operationId: getCourierTasks
      summary: 'Получение задач для курьера по дате и типу'
      tags:
        - courier-tasks
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
            example: '01-01-2023:14:30'
          description: 'Начальная дата в формате dd-MM-yyyy:HH:mm'
        - name: finishDate
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: '31-12-2023:14:30'
          description: 'Конечная дата в формате dd-MM-yyyy:HH:mm (опционально)'
        - name: type
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ECourierDeliveryType'
          description: 'Тип доставки'
      responses:
        200:
          description: 'Список задач курьера'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourierTask'
        400:
          description: 'Некорректные параметры запроса'

  /api/courierTask/togglePaid:
    put:
      operationId: togglePaidState
      summary: 'Переключение статуса оплаты задачи курьера'
      tags:
        - courier-tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  description: 'ID задачи курьера'
              required:
                - id
      responses:
        200:
          description: 'Статус оплаты успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourierTask'
        404:
          description: 'Задача не найдена'

  /api/places:
    get:
      operationId: getAllPlaces
      summary: 'получение всех мест'
      tags:
        - place
      responses:
        200:
          description: 'успешное получение всех мест'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
components:
  schemas:
    LoginData:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    Profile:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        surname:
          type: string
        role:
          type: string
      required:
        - id
        - name
        - surname
        - role

    MedicalService:
      type: object
      properties:
        id:
          type: number
        patient:
          type: string
        technitian:
          type: string
        typeWork:
          type: string
        fittingTimesArray:
          type: array
          items:
            type: string
        deadlineTime:
          type: string
      required:
        - id
        - patient
        - technitian
        - typeWork
        - fittingTimesArray
        - deadlineTime

    DailyTask:
      type: object
      properties:
        id:
          type: number
        time:
          type: string
        name:
          type: string
      required:
        - id
        - time
        - name

    Doctor:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        surname:
          type: string
        middleName:
          type: string
        clinic:
          type: string
        address:
          type: string
      required:
        - id
        - name
        - surname
        - middleName
        - clinic
        - address

    Technical:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        surname:
          type: string
        middleName:
          type: string
        avatar:
          type: string
      required:
        - id
        - name
        - surname
        - middleName

    StepTypeWork:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        material:
          type: string
        materialCost:
          type: string
        fullCost:
          type: number
      required:
        - id
        - name
        - material
        - materialCost
        - fullCost

    TypeWork:
      type: object
      properties:
        id:
          type: number
        typeProsthetics:
          type: string
          enum:
            - removable
            - non-removable
        steps:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/StepTypeWork'
        photo:
          type: string
      required:
        - id
        - typeProsthetics
        - steps
        - photo

    CategoryTechnicals:
      type: object
      properties:
        id:
          type: number
        categoryNumber:
          type: number
        technicians:
          type: array
          items:
            $ref: '#/components/schemas/Technical'
        typesWork:
          type: array
          items:
            $ref: '#/components/schemas/TypeWork'
      required:
        - id
        - categoryNumber
        - technicians
        - typesWork

    StorageItem:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        complectCount:
          type: number
        freeCount:
          type: number
        fullCount:
          type: number
        usedCount:
          type: number

    WorkDay:
      type: object
      properties:
        id:
          type: number
        earnings:
          type: number

    ExtendedWorkDay:
      allOf:
        - $ref: '#/components/schemas/WorkDay'

    PayrollData:
      allOf:
        - $ref: '#/components/schemas/Profile'
        - type: object
          properties:
            finishedServices:
              type: number
            nonWorkDays:
              type: number
            missedDeadlines:
              type: number
            workDaysInfo:
              type: array
              items:
                $ref: '#/components/schemas/WorkDay'
            workingRate:
              type: number
            pieceRate:
              type: number
            salary:
              type: number

    # НОВЫЕ СХЕМЫ ДЛЯ COURIER TASK
    ECourierDeliveryType:
      type: string
      enum:
        - delivery
        - pickup

    CreateCourierTaskDTO:
      type: object
      properties:
        startPlaceId:
          type: integer
          description: 'ID начального места'
        finishPlaceId:
          type: integer
          description: 'ID конечного места'
        courierName:
          type: string
          description: 'Имя курьера'
        serviceId:
          type: integer
          description: 'ID сервиса (опционально)'
        finishDate:
          type: string

    CourierTask:
      type: object
      properties:
        id:
          type: number
        startPlaceId:
          type: number
        finishPlaceId:
          type: number
        finishDate:
          type: string
        courierName:
          type: string
        paid:
          type: boolean
